In [159]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

data = {
    'Size_sqft': [500, 700, 900, 1100, 1300, 1500, 1700, 1900, 2100, 2300],
    'Price_lakh': [25, 30, 38, 45, 52, 60, 68, 75, 82, 90]
}

df = pd.DataFrame(data)
df

   Size_sqft  Price_lakh
0        500          25
1        700          30
2        900          38
3       1100          45
4       1300          52
5       1500          60
6       1700          68
7       1900          75
8       2100          82
9       2300          90

In [160]:
X = df[['Size_sqft']]   # 2D → sklearn requirement
y = df['Price_lakh']    # 1D

In [161]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=1
)

In [162]:
X_train

   Size_sqft
6       1700
4       1300
0        500
3       1100
1        700
7       1900
8       2100
5       1500

In [163]:
y_train

6    68
4    52
0    25
3    45
1    30
7    75
8    82
5    60
Name: Price_lakh, dtype: int64

In [164]:
X_test

   Size_sqft
2        900
9       2300

In [165]:
y_test

2    38
9    90
Name: Price_lakh, dtype: int64

In [166]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

In [167]:
model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [168]:
y_pred = model.predict(X_test_scaled)
y_pred = pd.DataFrame(y_pred, columns=['Predicted_Price'])
y_pred

   Predicted_Price
0        38.216216
1        89.265766

In [169]:
comparison = pd.DataFrame({
    'Size_sqft': X_test['Size_sqft'].values,
    'Actual_Price': y_test.values,
    'Predicted_Price': y_pred['Predicted_Price']
})

comparison

   Size_sqft  Actual_Price  Predicted_Price
0        900            38        38.216216
1       2300            90        89.265766

In [170]:
mae  = mean_absolute_error(y_test, y_pred)
mse  = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2   = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 0.4752252252252305
MSE : 0.29292468143819833
RMSE: 0.5412251670406674
R2  : 0.9995666794653281

***Model is so good!🔥 Now predict real world questions ..***

In [171]:
new_house = pd.DataFrame({'Size_sqft': [1600]}) # 1 row, 1 column.
new_house_scaled = scaler.transform(new_house)

predicted_price = model.predict(new_house_scaled)
predicted_price

array([63.74099099])