In [11]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [15]:
df = pd.DataFrame({
    'color': ['red','blue','green','purple','red','purple','blue','yellow']
})

In [16]:
df.head()

    color
0     red
1    blue
2   green
3  purple
4     red

In [17]:
encoder = OneHotEncoder()

In [34]:
sparse = encoder.fit_transform(df[['color']]).toarray()
# # or
# sparse = encoder.fit_transform(df).toarray()

In [35]:
final_df = pd.DataFrame(data=sparse, columns=encoder.get_feature_names_out())

In [33]:
final_df

   color_blue  color_green  color_purple  color_red  color_yellow
0         0.0          0.0           0.0        1.0           0.0
1         1.0          0.0           0.0        0.0           0.0
2         0.0          1.0           0.0        0.0           0.0
3         0.0          0.0           1.0        0.0           0.0
4         0.0          0.0           0.0        1.0           0.0
5         0.0          0.0           1.0        0.0           0.0
6         1.0          0.0           0.0        0.0           0.0
7         0.0          0.0           0.0        0.0           1.0

In [39]:
# New data

encoder.transform([['purple']]).toarray()

C:\Users\Rezon\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1., 0., 0.]])

In [40]:
final_df

   color_blue  color_green  color_purple  color_red  color_yellow
0         0.0          0.0           0.0        1.0           0.0
1         1.0          0.0           0.0        0.0           0.0
2         0.0          1.0           0.0        0.0           0.0
3         0.0          0.0           1.0        0.0           0.0
4         0.0          0.0           0.0        1.0           0.0
5         0.0          0.0           1.0        0.0           0.0
6         1.0          0.0           0.0        0.0           0.0
7         0.0          0.0           0.0        0.0           1.0