In [300]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sys
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

%matplotlib inline

In [301]:
df = pd.read_excel('flight_price.xlsx')
df.head()

       Airline Date_of_Journey    Source  ... Total_Stops Additional_Info  Price
0       IndiGo      24/03/2019  Banglore  ...    non-stop         No info   3897
1    Air India       1/05/2019   Kolkata  ...     2 stops         No info   7662
2  Jet Airways       9/06/2019     Delhi  ...     2 stops         No info  13882
3       IndiGo      12/05/2019   Kolkata  ...      1 stop         No info   6218
4       IndiGo      01/03/2019  Banglore  ...      1 stop         No info  13302

[5 rows x 11 columns]

In [302]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 1.8 MB

In [303]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

# Feature Engineering

In [304]:
df['Date'] = df['Date_of_Journey'].str.split('/').str[0]
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [305]:
df.head(2)

     Airline Date_of_Journey    Source Destination  ... Price Date Month  Year
0     IndiGo      24/03/2019  Banglore   New Delhi  ...  3897   24    03  2019
1  Air India       1/05/2019   Kolkata    Banglore  ...  7662    1    05  2019

[2 rows x 14 columns]

In [306]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(3), str(10)
memory usage: 2.0+ MB

In [307]:
df['Date'] = df['Date'].astype(dtype=int)
df['Month'] = df['Month'].astype(dtype=int)
df['Year'] = df['Year'].astype(dtype=int)

In [308]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  int64
 12  Month            10683 non-null  int64
 13  Year             10683 non-null  int64
dtypes: int64(4), str(10)
memory usage: 2.0 MB

In [309]:
df.drop('Date_of_Journey',axis=1, inplace=True)

In [310]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x: x.split(' ')[0])
df['Arrival_Hour'] = df['Arrival_Time'].str.split(':').str[0]
df['Arrival_Minute'] = df['Arrival_Time'].str.split(':').str[1]

In [311]:
df.drop('Arrival_Time', axis=1, inplace=True)

In [312]:
df.head(3)

       Airline    Source Destination  ...  Year Arrival_Hour Arrival_Minute
0       IndiGo  Banglore   New Delhi  ...  2019           01             10
1    Air India   Kolkata    Banglore  ...  2019           13             15
2  Jet Airways     Delhi      Cochin  ...  2019           04             25

[3 rows x 14 columns]

In [313]:
df['Arrival_Hour'] = df['Arrival_Hour'].astype(int)
df['Arrival_Minute'] = df['Arrival_Minute'].astype(int)

In [314]:
df['Dep_Hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_Min']=df['Dep_Time'].str.split(':').str[1]

In [315]:
df.head(3)

       Airline    Source Destination  ... Arrival_Minute Dep_Hour Dep_Min
0       IndiGo  Banglore   New Delhi  ...             10       22      20
1    Air India   Kolkata    Banglore  ...             15       05      50
2  Jet Airways     Delhi      Cochin  ...             25       09      25

[3 rows x 16 columns]

In [316]:
df.drop('Dep_Time',axis=1,inplace=True)

df['Dep_Hour'] = df['Dep_Hour'].astype(int)
df['Dep_Min'] = df['Dep_Min'].astype(int)

In [317]:
df.head(3)

       Airline    Source Destination  ... Arrival_Minute Dep_Hour Dep_Min
0       IndiGo  Banglore   New Delhi  ...             10       22      20
1    Air India   Kolkata    Banglore  ...             15        5      50
2  Jet Airways     Delhi      Cochin  ...             25        9      25

[3 rows x 15 columns]

In [318]:
df['Arrival_Min'] = df['Arrival_Minute']

In [319]:
df.head(2)

     Airline    Source Destination  ... Dep_Hour Dep_Min Arrival_Min
0     IndiGo  Banglore   New Delhi  ...       22      20          10
1  Air India   Kolkata    Banglore  ...        5      50          15

[2 rows x 16 columns]

In [320]:
df.drop('Arrival_Minute', axis=1, inplace=True)

# Handeling Categorical

In [321]:
df['Total_Stops'].unique()

<ArrowStringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [322]:
# df['Total_Stops']=df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop':1, '3 stops':3, np.nan:1, '4 stops':4})

In [323]:
df['Total_Stops'] = df['Total_Stops'].fillna('1 stop')

In [324]:
df['Total_Stops'].unique()

<ArrowStringArray>
['non-stop', '2 stops', '1 stop', '3 stops', '4 stops']
Length: 5, dtype: str

In [325]:
encoder = OrdinalEncoder(
    categories=[['non-stop','1 stop','2 stops','3 stops','4 stops']]
) # choto theke boro ba kom gurutto theke beshi gurutto er dike. 

df[['Total_Stops']] = encoder.fit_transform(df[['Total_Stops']])

In [326]:
df.head(3)

       Airline    Source Destination  ... Dep_Hour Dep_Min  Arrival_Min
0       IndiGo  Banglore   New Delhi  ...       22      20           10
1    Air India   Kolkata    Banglore  ...        5      50           15
2  Jet Airways     Delhi      Cochin  ...        9      25           25

[3 rows x 15 columns]

In [327]:
df.drop('Route', axis=1, inplace=True)

In [328]:
df.tail(3)

           Airline    Source Destination  ... Dep_Hour  Dep_Min Arrival_Min
10680  Jet Airways  Banglore       Delhi  ...        8       20          20
10681      Vistara  Banglore   New Delhi  ...       11       30          10
10682    Air India     Delhi      Cochin  ...       10       55          15

[3 rows x 14 columns]

In [329]:
df['Duration_Hour'] = df['Duration'].str.extract('(\d+)h') # h er age ja digit ase dhoro
df['Duration_Min']  = df['Duration'].str.extract('(\d+)m') # m er age ja digit ase dhoro

df['Duration_Hour'] = df['Duration_Hour'].fillna(0).astype(int)  
df['Duration_Min']  = df['Duration_Min'].fillna(0).astype(int)

In [330]:
df.drop('Duration', axis=1, inplace=True)

In [331]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Total_Stops      10683 non-null  float64
 4   Additional_Info  10683 non-null  str
 5   Price            10683 non-null  int64
 6   Date             10683 non-null  int64
 7   Month            10683 non-null  int64
 8   Year             10683 non-null  int64
 9   Arrival_Hour     10683 non-null  int64
 10  Dep_Hour         10683 non-null  int64
 11  Dep_Min          10683 non-null  int64
 12  Arrival_Min      10683 non-null  int64
 13  Duration_Hour    10683 non-null  int64
 14  Duration_Min     10683 non-null  int64
dtypes: float64(1), int64(10), str(4)
memory usage: 1.6 MB

In [332]:
df.head(4)

       Airline    Source Destination  ...  Arrival_Min Duration_Hour  Duration_Min
0       IndiGo  Banglore   New Delhi  ...           10             2            50
1    Air India   Kolkata    Banglore  ...           15             7            25
2  Jet Airways     Delhi      Cochin  ...           25            19             0
3       IndiGo   Kolkata    Banglore  ...           30             5            25

[4 rows x 15 columns]

In [333]:
df['Additional_Info'].value_counts()

Additional_Info
No info                         8345
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [334]:
df.drop(columns=['Additional_Info'], inplace=True)

In [335]:
df

           Airline    Source  ... Duration_Hour  Duration_Min
0           IndiGo  Banglore  ...             2            50
1        Air India   Kolkata  ...             7            25
2      Jet Airways     Delhi  ...            19             0
3           IndiGo   Kolkata  ...             5            25
4           IndiGo  Banglore  ...             4            45
...            ...       ...  ...           ...           ...
10678     Air Asia   Kolkata  ...             2            30
10679    Air India   Kolkata  ...             2            35
10680  Jet Airways  Banglore  ...             3             0
10681      Vistara  Banglore  ...             2            40
10682    Air India     Delhi  ...             8            20

[10683 rows x 14 columns]

In [336]:
df.isnull().sum()

Airline          0
Source           0
Destination      0
Total_Stops      0
Price            0
Date             0
Month            0
Year             0
Arrival_Hour     0
Dep_Hour         0
Dep_Min          0
Arrival_Min      0
Duration_Hour    0
Duration_Min     0
dtype: int64

# Pure Encoding

In [351]:
Ox = OneHotEncoder()
sparseMatrix = Ox.fit_transform(df[['Airline','Source','Destination']]).toarray()

In [352]:
df_dest = pd.DataFrame(sparseMatrix, columns=Ox.get_feature_names_out())

In [353]:
df_dest

       Airline_Air Asia  ...  Destination_New Delhi
0                   0.0  ...                    1.0
1                   0.0  ...                    0.0
2                   0.0  ...                    0.0
3                   0.0  ...                    0.0
4                   0.0  ...                    1.0
...                 ...  ...                    ...
10678               1.0  ...                    0.0
10679               0.0  ...                    0.0
10680               0.0  ...                    0.0
10681               0.0  ...                    1.0
10682               0.0  ...                    0.0

[10683 rows x 23 columns]

In [354]:
df_dest.isnull().sum()

Airline_Air Asia                             0
Airline_Air India                            0
Airline_GoAir                                0
Airline_IndiGo                               0
Airline_Jet Airways                          0
Airline_Jet Airways Business                 0
Airline_Multiple carriers                    0
Airline_Multiple carriers Premium economy    0
Airline_SpiceJet                             0
Airline_Trujet                               0
Airline_Vistara                              0
Airline_Vistara Premium economy              0
Source_Banglore                              0
Source_Chennai                               0
Source_Delhi                                 0
Source_Kolkata                               0
Source_Mumbai                                0
Destination_Banglore                         0
Destination_Cochin                           0
Destination_Delhi                            0
Destination_Hyderabad                        0
Destination_Kolkata                          0
Destination_New Delhi                        0
dtype: int64

In [355]:
df.isnull().sum()

Airline          0
Source           0
Destination      0
Total_Stops      0
Price            0
Date             0
Month            0
Year             0
Arrival_Hour     0
Dep_Hour         0
Dep_Min          0
Arrival_Min      0
Duration_Hour    0
Duration_Min     0
dtype: int64

In [359]:
df_dest.shape

(10683, 23)

In [360]:
df.shape

(10683, 14)

In [361]:
df.drop(['Airline', 'Source', 'Destination'], axis=1, inplace=True)

In [363]:
df = pd.concat([df, df_dest], axis=1)

In [364]:
df

       Total_Stops  Price  ...  Destination_Kolkata  Destination_New Delhi
0              0.0   3897  ...                  0.0                    1.0
1              2.0   7662  ...                  0.0                    0.0
2              2.0  13882  ...                  0.0                    0.0
3              1.0   6218  ...                  0.0                    0.0
4              1.0  13302  ...                  0.0                    1.0
...            ...    ...  ...                  ...                    ...
10678          0.0   4107  ...                  0.0                    0.0
10679          0.0   4145  ...                  0.0                    0.0
10680          0.0   7229  ...                  0.0                    0.0
10681          0.0  12648  ...                  0.0                    1.0
10682          2.0  11753  ...                  0.0                    0.0

[10683 rows x 34 columns]

In [365]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 34 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Stops                                10683 non-null  float64
 1   Price                                      10683 non-null  int64
 2   Date                                       10683 non-null  int64
 3   Month                                      10683 non-null  int64
 4   Year                                       10683 non-null  int64
 5   Arrival_Hour                               10683 non-null  int64
 6   Dep_Hour                                   10683 non-null  int64
 7   Dep_Min                                    10683 non-null  int64
 8   Arrival_Min                                10683 non-null  int64
 9   Duration_Hour                              10683 non-null  int64
 10  Duration_Min                               10683 non-null  int64
 11  Airline_Air Asia                           10683 non-null  float64
 12  Airline_Air India                          10683 non-null  float64
 13  Airline_GoAir                              10683 non-null  float64
 14  Airline_IndiGo                             10683 non-null  float64
 15  Airline_Jet Airways                        10683 non-null  float64
 16  Airline_Jet Airways Business               10683 non-null  float64
 17  Airline_Multiple carriers                  10683 non-null  float64
 18  Airline_Multiple carriers Premium economy  10683 non-null  float64
 19  Airline_SpiceJet                           10683 non-null  float64
 20  Airline_Trujet                             10683 non-null  float64
 21  Airline_Vistara                            10683 non-null  float64
 22  Airline_Vistara Premium economy            10683 non-null  float64
 23  Source_Banglore                            10683 non-null  float64
 24  Source_Chennai                             10683 non-null  float64
 25  Source_Delhi                               10683 non-null  float64
 26  Source_Kolkata                             10683 non-null  float64
 27  Source_Mumbai                              10683 non-null  float64
 28  Destination_Banglore                       10683 non-null  float64
 29  Destination_Cochin                         10683 non-null  float64
 30  Destination_Delhi                          10683 non-null  float64
 31  Destination_Hyderabad                      10683 non-null  float64
 32  Destination_Kolkata                        10683 non-null  float64
 33  Destination_New Delhi                      10683 non-null  float64
dtypes: float64(24), int64(10)
memory usage: 2.8 MB