In [59]:
import numpy as np
import pandas as pd

In [60]:
np.random.seed(500)

In [61]:
n_sample = 1000
class_0_ratio = 0.9

n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

In [62]:
n_class_1,n_class_0

(100, 900)

In [63]:
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

In [64]:
class_0

     feature_1  feature_2  target
0    -0.377364   0.841681       0
1     0.166759   1.004716       0
2     0.682802  -0.213977       0
3     1.921379  -0.375800       0
4    -0.197037   1.618610       0
..         ...        ...     ...
895  -1.162577  -0.908603       0
896  -0.007446  -0.804923       0
897  -0.421352  -0.822216       0
898   0.630879  -0.675865       0
899  -0.909484  -1.032625       0

[900 rows x 3 columns]

In [65]:
class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})
class_1

    feature_1  feature_2  target
0   -0.041067  -0.317556       1
1   -1.101576   0.305430       1
2    0.712771  -0.180804       1
3    0.243230   1.642339       1
4    1.761357   1.038187       1
..        ...        ...     ...
95  -1.168280  -0.344699       1
96  -0.374190  -1.920412       1
97   0.502950  -0.256821       1
98   0.454094  -0.429338       1
99  -0.423774  -0.433021       1

[100 rows x 3 columns]

In [66]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)
df

     feature_1  feature_2  target
0    -0.377364   0.841681       0
1     0.166759   1.004716       0
2     0.682802  -0.213977       0
3     1.921379  -0.375800       0
4    -0.197037   1.618610       0
..         ...        ...     ...
995  -1.168280  -0.344699       1
996  -0.374190  -1.920412       1
997   0.502950  -0.256821       1
998   0.454094  -0.429338       1
999  -0.423774  -0.433021       1

[1000 rows x 3 columns]

In [67]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

***We are doing Upscaling here:***

In [82]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [74]:
from sklearn.utils import resample

df_minority_upsampled = resample(
    df_minority,
    replace=True,
    n_samples=len(df_majority),
    random_state=42
    )

In [90]:
df_minority_upsampled.shape

(900, 3)

In [91]:
df_upsampled= pd.concat([df_majority, df_minority_upsampled])

In [99]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

***Upscaling Done.*** 💖

***Downsampling*** **-------------->**

In [101]:
class_3 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_4 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df_n = pd.concat([class_3,class_4]).reset_index(drop=True)

In [104]:
df_maj_ority = df_n[df_n['target']==0]
df_min_ority = df_n[df_n['target']==1]

In [105]:
from sklearn.utils import resample

df_maj_ority_upsampled = resample(
    df_maj_ority,
    replace=True,
    n_samples=len(df_min_ority),
    random_state=50
    )

In [108]:
df_upsampled_2= pd.concat([df_maj_ority_upsampled, df_min_ority])

df_upsampled_2['target'].value_counts()

target
0    100
1    100
Name: count, dtype: int64