In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('Algerian_forest_fires_dataset.csv', header=1)

In [4]:
df.isnull().sum()

day            0
month          1
year           1
Temperature    1
 RH            1
 Ws            1
Rain           1
FFMC           1
DMC            1
DC             1
ISI            1
BUI            1
FWI            1
Classes        2
dtype: int64

In [5]:
df[df.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,07,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [6]:
df = df.drop(index=122).reset_index(drop=True)

In [7]:
df[df.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
166,14,07,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [8]:
df.columns = df.columns.str.strip()
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes'],
      dtype='str')

In [9]:
df['Classes']

0       not fire
1       not fire
2       not fire
3       not fire
4       not fire
           ...
240         fire
241     not fire
242     not fire
243     not fire
244    not fire
Name: Classes, Length: 245, dtype: str

In [10]:
df['Classes'].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
Classes            1
not fire           1
not fire           1
Name: count, dtype: int64

In [11]:
df['Classes'] = df['Classes'].astype(str).str.strip().str.lower()

In [12]:
df['Classes'].value_counts()

Classes
fire        137
not fire    106
classes       1
Name: count, dtype: int64

In [13]:
df = df[df['Classes'].isin(['fire', 'not fire'])]
df = df.reset_index(drop=True)

In [14]:
df['Classes'].value_counts()

Classes
fire        137
not fire    106
Name: count, dtype: int64

In [15]:
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,fire
239,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,not fire
240,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire
241,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire
242,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire

In [16]:
df['Classes'] = (df['Classes'] == 'fire').astype(int)

In [17]:
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,0
4,05,06,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,26,09,2012,30,65,14,0,85.4,16,44.5,4.5,16.9,6.5,1
239,27,09,2012,28,87,15,4.4,41.1,6.5,8,0.1,6.2,0,0
240,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0
241,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0
242,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0

In [18]:
df.isnull().sum()

day            0
month          0
year           0
Temperature    0
RH             0
Ws             0
Rain           0
FFMC           0
DMC            0
DC             0
ISI            0
BUI            0
FWI            0
Classes        0
dtype: int64

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    str
 1   month        243 non-null    str
 2   year         243 non-null    str
 3   Temperature  243 non-null    str
 4   RH           243 non-null    str
 5   Ws           243 non-null    str
 6   Rain         243 non-null    str
 7   FFMC         243 non-null    str
 8   DMC          243 non-null    str
 9   DC           243 non-null    str
 10  ISI          243 non-null    str
 11  BUI          243 non-null    str
 12  FWI          243 non-null    str
 13  Classes      243 non-null    int64
dtypes: int64(1), str(13)
memory usage: 35.6 KB

In [20]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes'],
      dtype='str')

In [21]:
df[['Temperature', 'RH', 'Ws']] = df[['Temperature', 'RH', 'Ws']].astype(int)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    str
 1   month        243 non-null    str
 2   year         243 non-null    str
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    str
 7   FFMC         243 non-null    str
 8   DMC          243 non-null    str
 9   DC           243 non-null    str
 10  ISI          243 non-null    str
 11  BUI          243 non-null    str
 12  FWI          243 non-null    str
 13  Classes      243 non-null    int64
dtypes: int64(4), str(10)
memory usage: 34.1 KB

In [23]:
df[['Rain', 'FFMC','DMC', 'DC', 'ISI', 'BUI', 'FWI']] = df[['Rain', 'FFMC','DMC', 'DC', 'ISI', 'BUI', 'FWI']].astype(float)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          243 non-null    str
 1   month        243 non-null    str
 2   year         243 non-null    str
 3   Temperature  243 non-null    int64
 4   RH           243 non-null    int64
 5   Ws           243 non-null    int64
 6   Rain         243 non-null    float64
 7   FFMC         243 non-null    float64
 8   DMC          243 non-null    float64
 9   DC           243 non-null    float64
 10  ISI          243 non-null    float64
 11  BUI          243 non-null    float64
 12  FWI          243 non-null    float64
 13  Classes      243 non-null    int64
dtypes: float64(7), int64(4), str(3)
memory usage: 28.7 KB

In [25]:
df.reset_index()

,index,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,0,01,06,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0
1,1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0
2,2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0
3,3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0
4,4,05,06,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,238,26,09,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1
239,239,27,09,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0
240,240,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0
241,241,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0
242,242,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0

In [26]:
df.to_csv('cleaned_dataset.csv')

In [27]:
df_copy = df.copy()

In [28]:
df_copy.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0
4,05,06,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0

In [29]:
df_copy

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0
3,04,06,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0
4,05,06,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,26,09,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,1
239,27,09,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,0
240,28,09,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,0
241,29,09,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,0
242,30,09,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,0

In [30]:
df_copy.drop(columns=['day', 'month', 'year'], inplace=True)

In [31]:
df_copy

     Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  FWI  Classes
0             29  57  18   0.0  65.7   3.4   7.6  1.3   3.4  0.5        0
1             29  61  13   1.3  64.4   4.1   7.6  1.0   3.9  0.4        0
2             26  82  22  13.1  47.1   2.5   7.1  0.3   2.7  0.1        0
3             25  89  13   2.5  28.6   1.3   6.9  0.0   1.7  0.0        0
4             27  77  16   0.0  64.8   3.0  14.2  1.2   3.9  0.5        0
..           ...  ..  ..   ...   ...   ...   ...  ...   ...  ...      ...
238           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9  6.5        1
239           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2  0.0        0
240           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4  0.2        0
241           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1  0.7        0
242           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8  0.5        0

[243 rows x 11 columns]

In [33]:
df_copy.to_csv('ready_cleaned_df.csv')